<?php

namespace app\controllers;

use Yii;


class PostController extends AppController {

    public function actionTest() {
        $bands = [
            'Meshuggah',
            'The Tony Danza Tapdance Extravaganza',
            'Ion Dissonance',
            'The Dillinger Escape Plan'
        ];

//        var_dump(Yii::$app);
        return $this->render('test', ['bands' => $bands]);
    }

    public function actionTest2() {
        $bands = [
            'Meshuggah',
            'The Tony Danza Tapdance Extravaganza',
            'Ion Dissonance',
            'The Dillinger Escape Plan'
        ];

//        var_dump(Yii::$app);
        $this->view->title = 'Тестовая страница';
        $this->layout = 'new';
        return $this->render('test', ['bands' => $bands]);
    }


    public function beforeAction($action) {
//        debugPrint($action);

        if ($action->id == 'show2') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
        // TODO: Change the autogenerated stub (TODO example)
    }

    public function actionIndex() {

        $this->view->title = 'О записях';
        $this->layout = 'new';
        return $this->render('index');
    }

    public function actionShow2() {

        if (Yii::$app->request->isAjax) {
//            debugPrint($_POST);
            debugPrint(Yii::$app->request->post());
            return 'Ajax request worked!';
        }

        $this->view->title = 'Просмотр записи';
        $this->layout = 'new';
//        $this->view->registerMetaTag(['name'=>'keywords', 'content'=>'yii, yii2, learning']);
//        $this->view->registerMetaTag(['name'=>'description', 'content'=>'моё приложение на фреймворке Yii2 (свой шаблон)']);
        return $this->render('show');
    }
}
