<?php

namespace app\controllers;

use Yii;

class PostController extends AppController {

    public function actionTest() {
        $bands = [
            'Meshuggah',
            'The Tony Danza Tapdance Extravaganza',
            'Ion Dissonance',
            'The Dillinger Escape Plan'
        ];

//        var_dump(Yii::$app);
        return $this->render('test', ['bands' => $bands]);
    }

    public function actionTest2() {
        $bands = [
            'Meshuggah',
            'The Tony Danza Tapdance Extravaganza',
            'Ion Dissonance',
            'The Dillinger Escape Plan'
        ];

//        var_dump(Yii::$app);
        $this->layout = 'simplified';
        return $this->render('test', ['bands' => $bands]);
    }

    public function actionShow2() {
        $this->layout = 'simplified';
        return $this->render('show');
    }

    public function beforeAction($action) {
//        debugPrint($action);
        if ($action->id == 'index') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
        // TODO: Change the autogenerated stub
    }

    public function actionIndex() {

        if(Yii::$app->request->isAjax) {
//            debugPrint($_POST);
            debugPrint(Yii::$app->request->post());
            return 'Ajax request worked!';
        }

        $this->layout = 'simplified';
        return $this->render('index');
    }
}
